[custom.all.linux]
type = "local"
path = "."
ipkg = "linux.ipkg"
test = "test/test.ipkg"

[custom.all.cptr]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-cptr"
commit = "latest:main"
ipkg   = "cptr.ipkg"
